/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

// Import the component files

import { Route as rootRoute } from './routes/__root'
import { Route as ItemsSlugImport } from './routes/items/$slug'
import { Route as ItemsIndexImport } from './routes/items/index'
import { Route as ItemsNewImport } from './routes/items/new'
import { Route as IndexImport } from './routes/index'

// Create/Update the route tree

const ItemsSlugRoute = ItemsSlugImport.update({
  path: '/items/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ItemsIndexRoute = ItemsIndexImport.update({
  path: '/items/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsNewRoute = ItemsNewImport.update({
  path: '/items/new',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexImport
      parentRoute: typeof rootRoute
    }
    '/items/$slug': {
      id: '/items/$slug'
      path: '/items/$slug'
      fullPath: '/items/$slug'
      preLoaderRoute: typeof ItemsSlugImport
      parentRoute: typeof rootRoute
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ItemsIndexRoute,
  ItemsSlugRoute,
  ItemsNewRoute,
})

/* prettier-ignore-end */
